### ISSUE TITLE
immobiliare script does not retrieve some values

### ISSUE THREAD

**Issue by EmanueleCannizzaro** [fgrillo89/real-estate-scraper#1]
When I run the immobiliare script, I get the following warning:

    Latitude was not retrieved because 'NoneType' object has no attribute 'text'
    Longitude was not retrieved because 'NoneType' object has no attribute 'text'
    AddressDeep was not retrieved because 'NoneType' object has no attribute 'text'
    Region was not retrieved because 'NoneType' object has no attribute 'text'
    Province was not retrieved because 'NoneType' object has no attribute 'text'
    City was not retrieved because 'NoneType' object has no attribute 'text'
    Macrozone was not retrieved because 'NoneType' object has no attribute 'text'
    Microzone was not retrieved because 'NoneType' object has no attribute 'text'
    StreetNumber was not retrieved because 'NoneType' object has no attribute 'text'

Probably the schema of the result page has changed.

**Comment by fgrillo89** [comment]
This issue is now resolved. I updated the function that retrieves those itemd to match the new html of the result pages.
